### ISSUE TITLE
error: unrecognized arguments

### ISSUE THREAD

**Issue by cjj1120** [norbeyandresg/hades#10]
I received this error message, any idea where did I do wrong? I added the Client ID and Client secret on hades.py , installed spotipy and youtube_dl, copy playlist URI and entered code as shown below:

 `python hades.py [-e] 'spotify:playlist:37i9dQZF1E8UAe9z9xSDuU'  `

Error message:

`hades.py: error: unrecognized arguments: spotify:playlist:37i9dQZF1E8UAe9z9xSDuU `

**Comment by norbeyandresg** [comment]
@wilcockj can you check this out and to make sure that the embed flag doesn't generate the issue?

**Comment by wilcockj** [comment]
So it looks like the issue here is the '[-e]' in the command
if you do the command
```
python hades.py -e 'spotify:playlist:37i9dQZF1E8UAe9z9xSDuU' 
```
The program will download the songs and embed the thumbnail of the youtube video it downloads into the mp3.

And then the following command will download the songs without the thumbnail
```
python hades.py 'spotify:playlist:37i9dQZF1E8UAe9z9xSDuU' 
```
Maybe we should have examples in the documentation in order to make it more clear?
What do you think @norbeyandresg ?

**Comment by norbeyandresg** [comment]
Sure. I'm going to update the documentation to make it more clear

**Comment by cjj1120** [comment]
> So it looks like the issue here is the '[-e]' in the command
> 
> if you do the command
> 
> ```
> 
> python hades.py -e 'spotify:playlist:37i9dQZF1E8UAe9z9xSDuU' 
> 
> ```
> 
> The program will download the songs and embed the thumbnail of the youtube video it downloads into the mp3.
> 
> 
> 
> And then the following command will download the songs without the thumbnail
> 
> ```
> 
> python hades.py 'spotify:playlist:37i9dQZF1E8UAe9z9xSDuU' 
> 
> ```
> 
> Maybe we should have examples in the documentation in order to make it more clear?
> 
> What do you think @norbeyandresg ?

Thanks, I now have another issue with FFMPEG. It says that it's not found, though I've downloaded with code below: 

`pip install ffmpeg-python `

**Comment by norbeyandresg** [comment]
Did you use the requirements.txt to install all the dependencies?

**Comment by cjj1120** [comment]
> Did you use the requirements.txt to install all the dependencies?

Yes I did

**Comment by cjj1120** [comment]
Got it already, it's working i rerun the codes and it works thanks guys!
