### ISSUE TITLE
Follow the song naming convention

### ISSUE THREAD

**Issue by poloturiot** [norbeyandresg/hades#16]
Not really an issue but more a suggestion.
It would be nice if the generated mp3s could follow the song naming convention which is "[Artist name] - [Song name].mp3". Right now it is "[Song name] - [Artist name].mp3".

**Comment by Tomasroma64** [comment]
You can easily change it by swapping around [this](https://github.com/norbeyandresg/hades/blob/main/hades.py#L64) to your preference
But maybe a command-line option/argument could be added to have a setting functionality

**Comment by norbeyandresg** [comment]
Song naming convention was changed in the last merge to `[artist name] - [track name]`
