### ISSUE TITLE
noob error

### ISSUE THREAD

**Issue by SouzaEmerson** [norbeyandresg/hades#17]
can you please help me? I don't know what is going on.

ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.
Traceback (most recent call last):
  File "hades.py", line 131, in <module>
    hades.download_tracks()
  File "hades.py", line 119, in download_tracks
    os.rename(src, dst)

**Comment by norbeyandresg** [comment]
Did you install the requirements file? if so, try to update the `youtube-dl` package

**Comment by SouzaEmerson** [comment]
sorry solved: 

https://stackoverflow.com/a/50287946/14375840
