### ISSUE TITLE
List Index Out of Range

### ISSUE THREAD

**Issue by awsomemanNever** [norbeyandresg/hades#2]
So, second issue yay
Traceback (most recent call last):
  File "hades.py", line 102, in <module>
    hades.download_tracks()
  File "hades.py", line 90, in download_tracks
    url = "https://www.youtube.com/watch?v=" + video_ids[0]
IndexError: list index out of range

This is what i get when i get to song 30 of 100 in my playlist
https://open.spotify.com/playlist/0xGFYsNJ8xynWp1mpwcOQm
^ thats the public playlist

**Comment by norbeyandresg** [comment]
Thanks @FelixIsaac  for the contribution fixing this little issues. @awsomemanNever Let me know if all works fine to close this issue

**Comment by awsomemanNever** [comment]
@norbeyandresg it works. I finally have all 100 songs downloaded.  Thank you so much @FelixIsaac for implementing the fix
