### ISSUE TITLE
Console Error When trying to run script

### ISSUE THREAD

**Issue by TheFryz** [norbeyandresg/hades#21]
D:\Youtube Downloader\Lib>python hades_ui.py --pl_uri https://open.spotify.com/playlist/1VANr5wE3tsOuGnSMGchIk?si=20d8adbbbcbf41f4
Traceback (most recent call last):
  File "D:\Youtube Downloader\Lib\hades_ui.py", line 111, in <module>
    HadesUI(parser.parse_args().pl_uri)
  File "D:\Youtube Downloader\Lib\hades_ui.py", line 18, in __init__
    self.hades = Hades()
  File "D:\Youtube Downloader\Lib\hades.py", line 33, in __init__
    self.auth_manager = SpotifyClientCredentials(
  File "C:\Python39\lib\site-packages\spotipy\oauth2.py", line 157, in __init__
    self.client_id = client_id
  File "C:\Python39\lib\site-packages\spotipy\oauth2.py", line 109, in client_id
    self._client_id = _ensure_value(val, "client_id")
  File "C:\Python39\lib\site-packages\spotipy\oauth2.py", line 77, in _ensure_value
    raise SpotifyOauthError(msg)
spotipy.oauth2.SpotifyOauthError: No client_id. Pass it or set a SPOTIPY_CLIENT_ID environment variable.

**Comment by TheFryz** [comment]
And yes, i left all three of my credentials inside of hades.py

**Comment by AlexB02** [comment]
> And yes, i left all three of my credentials inside of hades.py

By leaving them inside hades.py, do you mean you have hardcoded your credentials in?

**Comment by TheFryz** [comment]
I right clicked and edited hades.py and inserted by credentails inside the "", i did this due becuase the other version made me do it

**Comment by Tomasroma64** [comment]
I tried to replicate this error by hardcoding the credentials in, but everything is still working fine. 

Either way, I would suggest adding the credentials to your System Variables so no code has to be altered :D

**Comment by AlexB02** [comment]
Sounds like it could be an issue with the credentials you're providing, have you double checked they're all correct?

**Comment by norbeyandresg** [comment]
@TheFryz how are you configuring your credentials?

**Comment by collinhawks** [comment]
Having the exact same issue.. I've tried entering the code into CLIENT_ID inside the "". I've tried setting environment variables with "CLIENT_ID" as the name and the value is the code... I'm stuck. Any suggestions??

**Comment by collinhawks** [comment]
Is it because I am on windows??

**Comment by Tomasroma64** [comment]
I don't think it has anything to do with being on Windows directly, but I'm still not sure where the error is coming from.
Check that everything has been installed correctly.

Would you mind sending more error logs when
- Hardcoding the credentials
- Using System Variables (Edit the system environment variables > Environment Variables... > System Variables > New...)

System Variables should look something like this, where red are the credentials:
<img width="414" alt="System variables example" src="https://user-images.githubusercontent.com/38633386/120159459-8821d900-c1f5-11eb-9308-708ff47913da.png">

**Comment by Tomasroma64** [comment]
Remember that for changes in the environment variables to take place, you will have to restart the CMD you're using. Just close it and open it back up again and the changes should take place.

**Comment by norbeyandresg** [comment]
Closed by inactivity
