### ISSUE TITLE
Faster fork of YouTube-DL

### ISSUE THREAD

**Issue by k-gaia** [norbeyandresg/hades#29]
Switching the original youtube-dl library to this [new fork](https://github.com/yt-dlp/yt-dlp) seems to improve download speed drastically, at least on my end.

Great tool btw, I'll admit tho it took me way too long to realise the URI had an extra bit at the end I just didn't notice ... 💀

**Comment by Tomz3n** [comment]
Indeed, easily fixed by replacing line 15 to: `from yt_dlp import YoutubeDL` and of course switching the requirement file to require yt_dlp instead of youtube_dl

**Comment by norbeyandresg** [comment]
`yt-dlp` support added  on [commit](https://github.com/norbeyandresg/hades/commit/43739505be79f38af558e246e18abc3a5e2447e3)
